/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
     colors: {
  "primary-fixed": "rgb(var(--c-primary-fixed) / <alpha-value>)",
  "surface-container-high": "rgb(var(--c-surface-container-high) / <alpha-value>)",
  "on-secondary-fixed": "rgb(var(--c-on-secondary-fixed) / <alpha-value>)",
  "on-secondary-fixed-variant": "rgb(var(--c-on-secondary-fixed-variant) / <alpha-value>)",
  "inverse-primary": "rgb(var(--c-inverse-primary) / <alpha-value>)",
  outline: "rgb(var(--c-outline) / <alpha-value>)",
  "on-tertiary-fixed": "rgb(var(--c-on-tertiary-fixed) / <alpha-value>)",
  "tertiary-container": "rgb(var(--c-tertiary-container) / <alpha-value>)",
  "secondary-fixed-dim": "rgb(var(--c-secondary-fixed-dim) / <alpha-value>)",
  "surface-container-highest": "rgb(var(--c-surface-container-highest) / <alpha-value>)",
  "on-background": "rgb(var(--c-on-background) / <alpha-value>)",
  "surface-container-lowest": "rgb(var(--c-surface-container-lowest) / <alpha-value>)",
  primary: "rgb(var(--c-primary) / <alpha-value>)",
  surface: "rgb(var(--c-surface) / <alpha-value>)",
  "on-secondary": "rgb(var(--c-on-secondary) / <alpha-value>)",
  "surface-container-low": "rgb(var(--c-surface-container-low) / <alpha-value>)",
  "surface-variant": "rgb(var(--c-surface-variant) / <alpha-value>)",
  "primary-container": "rgb(var(--c-primary-container) / <alpha-value>)",
  "surface-container": "rgb(var(--c-surface-container) / <alpha-value>)",
  "on-surface-variant": "rgb(var(--c-on-surface-variant) / <alpha-value>)",
  "on-secondary-container": "rgb(var(--c-on-secondary-container) / <alpha-value>)",
  "secondary-container": "rgb(var(--c-secondary-container) / <alpha-value>)",
  "on-primary-container": "rgb(var(--c-on-primary-container) / <alpha-value>)",
  "on-primary-fixed": "rgb(var(--c-on-primary-fixed) / <alpha-value>)",
  "on-tertiary-fixed-variant": "rgb(var(--c-on-tertiary-fixed-variant) / <alpha-value>)",
  "surface-bright": "rgb(var(--c-surface-bright) / <alpha-value>)",
  "surface-dim": "rgb(var(--c-surface-dim) / <alpha-value>)",
  error: "rgb(var(--c-error) / <alpha-value>)",
  "on-primary-fixed-variant": "rgb(var(--c-on-primary-fixed-variant) / <alpha-value>)",
  "outline-variant": "rgb(var(--c-outline-variant) / <alpha-value>)",
  "tertiary-fixed": "rgb(var(--c-tertiary-fixed) / <alpha-value>)",
  "on-surface": "rgb(var(--c-on-surface) / <alpha-value>)",
  "on-error-container": "rgb(var(--c-on-error-container) / <alpha-value>)",
  "tertiary-fixed-dim": "rgb(var(--c-tertiary-fixed-dim) / <alpha-value>)",
  "on-error": "rgb(var(--c-on-error) / <alpha-value>)",
  "on-tertiary-container": "rgb(var(--c-on-tertiary-container) / <alpha-value>)",
  "surface-tint": "rgb(var(--c-surface-tint) / <alpha-value>)",
  "error-container": "rgb(var(--c-error-container) / <alpha-value>)",
  background: "rgb(var(--c-background) / <alpha-value>)",
  "on-tertiary": "rgb(var(--c-on-tertiary) / <alpha-value>)",
  "inverse-surface": "rgb(var(--c-inverse-surface) / <alpha-value>)",
  secondary: "rgb(var(--c-secondary) / <alpha-value>)",
  tertiary: "rgb(var(--c-tertiary) / <alpha-value>)",
  "secondary-fixed": "rgb(var(--c-secondary-fixed) / <alpha-value>)",
  "primary-fixed-dim": "rgb(var(--c-primary-fixed-dim) / <alpha-value>)",
  "inverse-on-surface": "rgb(var(--c-inverse-on-surface) / <alpha-value>)",
  "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
},
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-desktop": "2rem",
        "space-3xl": "4rem",
        "space-5xl": "8rem",
        "space-4xl": "6rem",
        "space-xl": "2rem",
        "space-sm": "0.75rem",
        "space-3xs": "0.125rem",
        "space-lg": "1.5rem",
        "container-max": "1280px",
        "space-2xl": "3rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Plus Jakarta Sans"],
        "label-code": ["JetBrains Mono"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-caps": ["Plus Jakarta Sans"],
        display: ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "display-mobile": ["Plus Jakarta Sans"],
      },
      fontSize: {
  "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" }],
  "body-lg": ["17px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "400" }],
  "body-md": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
  "headline-xl": ["34px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "700" }],
  "label-code": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
  "headline-xl-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.025em", fontWeight: "700" }],
  "headline-lg": ["26px", { lineHeight: "32px", letterSpacing: "-0.025em", fontWeight: "700" }],
  "headline-md": ["19px", { lineHeight: "26px", letterSpacing: "-0.02em", fontWeight: "600" }],
  "label-caps": ["10px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "700" }],
  display: ["42px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
  "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
  "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.015em", fontWeight: "600" }],
  "display-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.03em", fontWeight: "800" }],
},
    },
  },
  plugins: [],
};